version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo "Construyendo imagen de Docker"
      - docker build -t my-app ./app

artifacts:
  files:
    - '**/*'

